{% set name = "schwifty" %}
{% set version = "2024.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/schwifty-{{ version }}.tar.gz
  sha256: d0aaed03168403b433de515d663df09516941ae70152850da3afe3c242255f6a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - importlib_resources >=5.10
    - typing-extensions >=4.0.1
    - pycountry
    - rstr

test:
  source_files:
    - tests
  imports:
    - schwifty
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - pydantic >=2.0
    - python {{ python_min }}

about:
  home: http://github.com/mdomke/schwifty
  summary: Validate/generate IBANs and BICs
  doc_url: https://pythonhosted.org/schwifty/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
