{% set name = "schwifty" %}
{% set version = "2023.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schwifty-{{ version }}.tar.gz
  sha256: 606dd521a9aa9e258bc3a0221f6a820aa36678ab2cfb6f84ac95c70c1ce6e2fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - importlib_resources
    - iso3166
    - pycountry
    - python >=3.8

test:
  source_files:
    - tests
  imports:
    - schwifty
    - schwifty.checksum
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - pydantic >=2.0

about:
  home: http://github.com/mdomke/schwifty
  summary: Validate/generate IBANs and BICs
  doc_url: https://pythonhosted.org/schwifty/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
