{% set name = "schwifty" %}
{% set version = "2024.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schwifty-{{ version }}.tar.gz
  sha256: 58742387d874966bf764337db3a2e76610f1ede2fa1db056b84067f741f2e396

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - importlib_resources >=5.10
    - pycountry
    - python >=3.8

test:
  source_files:
    - tests
  imports:
    - schwifty
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - pydantic >=2.0

about:
  home: http://github.com/mdomke/schwifty
  summary: Validate/generate IBANs and BICs
  doc_url: https://pythonhosted.org/schwifty/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
