{% set name = "schwifty" %}
{% set version = "2024.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schwifty-{{ version }}.tar.gz
  sha256: df6f98a4321772095dc2dc54e6cf55e9ca2783bd048b21207fd402358744be9d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - importlib_resources >=5.10
    - typing-extensions >=4.0.1
    - pycountry
    - rstr

test:
  source_files:
    - tests
  imports:
    - schwifty
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - pydantic >=2.0

about:
  home: http://github.com/mdomke/schwifty
  summary: Validate/generate IBANs and BICs
  doc_url: https://pythonhosted.org/schwifty/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
