schema_version: 1

context:
  name: schwifty
  version: 2025.7.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/schwifty-${{ version }}.tar.gz
  sha256: a98af4f00056ba5fa6f25b7eb1749c50c481c1813b6500c88433e34ef45c19f9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4.0.1
    - importlib-resources >=5.10
    - pycountry
    - rstr

tests:
  - python:
      imports:
        - schwifty
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests
    requirements:
      run:
        - pytest
        - pydantic >=2.0
        - python ${{ python_min }}.*
    script:
      - pytest -vvv --capture=tee-sys tests

about:
  summary: Validate/generate IBANs and BICs
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/mdomke/schwifty
  documentation: https://pythonhosted.org/schwifty/

extra:
  recipe-maintainers:
    - thewchan
